BOARD_TAG    = atmega328
ARDUINO_PORT = /dev/ttyUSB0
ARDUINO_LIBS = ArtNet EtherCard EEPROM FastLED NanodeMAC Wire LiquidCrystal_I2C
## ARDUINO_DIR  = /home/jerome/Documents/arduino-1.0.1
## ARDUINO_SKETCHBOOK = /home/jerome/Documents/sketchbook

## AVRDUDE = $(ARDUINO_DIR)/hardware/tools/avrdude
## AVRDUDE_CONF = $(ARDUINO_DIR)/hardware/tools/avrdude.conf

include $(ARDMK_DIR)/Arduino.mk

